// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEFUO7ipyjVpfgyXetCBwaYkJ7a_mZcLU',
    appId: '1:1044282870883:web:fc0518b41077518e413c56',
    messagingSenderId: '1044282870883',
    projectId: 'vehicle-list-app-46337',
    authDomain: 'vehicle-list-app-46337.firebaseapp.com',
    storageBucket: 'vehicle-list-app-46337.firebasestorage.app',
    measurementId: 'G-MSH2EF1V56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIrfz1BS9OS81Iv3GWmjSJtB7bG_3FfyY',
    appId: '1:1044282870883:android:2e997fd29f6a6ac5413c56',
    messagingSenderId: '1044282870883',
    projectId: 'vehicle-list-app-46337',
    storageBucket: 'vehicle-list-app-46337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN078UaTyvyf-10KO1O6a1l-VAxPkRjUA',
    appId: '1:1044282870883:ios:8a27da8217b4c03f413c56',
    messagingSenderId: '1044282870883',
    projectId: 'vehicle-list-app-46337',
    storageBucket: 'vehicle-list-app-46337.firebasestorage.app',
    iosBundleId: 'com.example.vehicleListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN078UaTyvyf-10KO1O6a1l-VAxPkRjUA',
    appId: '1:1044282870883:ios:8a27da8217b4c03f413c56',
    messagingSenderId: '1044282870883',
    projectId: 'vehicle-list-app-46337',
    storageBucket: 'vehicle-list-app-46337.firebasestorage.app',
    iosBundleId: 'com.example.vehicleListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEFUO7ipyjVpfgyXetCBwaYkJ7a_mZcLU',
    appId: '1:1044282870883:web:cefc82929afd5d1d413c56',
    messagingSenderId: '1044282870883',
    projectId: 'vehicle-list-app-46337',
    authDomain: 'vehicle-list-app-46337.firebaseapp.com',
    storageBucket: 'vehicle-list-app-46337.firebasestorage.app',
    measurementId: 'G-EBPZGXTXLD',
  );
}
